@startuml
title Paquetes principales - domain

package domain {
  package models {
    class Entity
    class DTO
  }
  package mappers {
    class EntityMapper
  }
  package managers {
    class AuthManager
  }
  package services {
    class BusinessService
  }
  package usecases {
    class GetItemsUseCase
    class SaveItemUseCase
  }
}

usecases --> models
usecases --> mappers
services --> managers
@enduml
