@startuml
title Contexto - Backoffice

actor "Administrador" as ADMIN
component "Backoffice" as BACKOFFICE
component "Orchestrator" as ORCH
component "Monitoring" as MON

ADMIN --> BACKOFFICE: Administra
BACKOFFICE --> ORCH: API / Config
BACKOFFICE --> MON: Métricas

@enduml
