@startuml
title Secuencia típica: pantalla -> UseCase -> Repositorio -> DataSource

actor User
participant "Feature (UI/VM)" as FEAT
participant "UseCase (Domain)" as UC
participant "Repo (Domain interface)" as REPO
participant "DataSource (Data impl)" as DS

User -> FEAT : Interaction (click / input)
FEAT -> UC : ejecutar(params)
UC -> REPO : obtenerDatos(params)
REPO -> DS : consultaRemote()/consultaLocal()
DS --> REPO : datosDTO
REPO --> UC : datosDomain
UC --> FEAT : resultado
FEAT --> User : render
@enduml
