@startuml
title Context - Services

actor "Orchestrator" as ORCH
component "Service A" as SVC_A
component "Service B" as SVC_B
component "Message Broker" as BROKER

ORCH --> SVC_A
ORCH --> SVC_B
SVC_A --> BROKER
SVC_B --> BROKER

@enduml
